INSERT INTO LISTA_REPRODUCCION (NOMBRE, DESCRIPCION) VALUES ('Playlist 1', 'Descripcion de la playlist 1');
INSERT INTO LISTA_REPRODUCCION (NOMBRE, DESCRIPCION) VALUES ('Playlist 2', 'Descripcion de la playlist 2');
INSERT INTO LISTA_REPRODUCCION (NOMBRE, DESCRIPCION) VALUES ('Playlist 3', 'Descripcion de la playlist 3');
INSERT INTO CANCION (TITULO, ARTISTA, ALBUM, ANNO, GENERO, LISTA_REPRODUCCION_ID) VALUES ('Titulo 1', 'Artista 1', 'Album 1', 2020, 'Genero 1', 1);
INSERT INTO CANCION (TITULO, ARTISTA, ALBUM, ANNO, GENERO, LISTA_REPRODUCCION_ID) VALUES ('Titulo 2', 'Artista 2', 'Album 2', 2021, 'Genero 1', 1);
INSERT INTO CANCION (TITULO, ARTISTA, ALBUM, ANNO, GENERO, LISTA_REPRODUCCION_ID) VALUES ('Titulo 3', 'Artista 3', 'Album 3', 2022, 'Genero 2', 1);
INSERT INTO CANCION (TITULO, ARTISTA, ALBUM, ANNO, GENERO, LISTA_REPRODUCCION_ID) VALUES ('Titulo 4', 'Artista 4', 'Album 4', 2023, 'Genero 3', 2);
INSERT INTO CANCION (TITULO, ARTISTA, ALBUM, ANNO, GENERO, LISTA_REPRODUCCION_ID) VALUES ('Titulo 5', 'Artista 4', 'Album 4', 2024, 'Genero 3', 2);
INSERT INTO CANCION (TITULO, ARTISTA, ALBUM, ANNO, GENERO, LISTA_REPRODUCCION_ID) VALUES ('Titulo 6', 'Artista 6', 'Album 6', 2005, 'Genero 3', 3); 
